namespace AutoScrapper
{
    public static class Tokens
    {
        public const string MOD_DESCRIPTION = "AUTO_SCRAPPER_MOD_DESCRIPTION";
        public const string AUTOMAGICALLY_SCRAPPED = "AUTO_SCRAPPER_AUTOMAGICALLY_SCRAPPED";
        public const string WHITE_ITEMS = "AUTO_SCRAPPER_WHITE_ITEMS";
        public const string GREEN_ITEMS = "AUTO_SCRAPPER_GREEN_ITEMS";
        public const string RED_ITEMS = "AUTO_SCRAPPER_RED_ITEMS";
        public const string YELLOW_ITEMS = "AUTO_SCRAPPER_YELLOW_ITEMS";
        public const string WHITE_ITEMS_PLURAL = "AUTO_SCRAPPER_WHITE_ITEMS_PLURAL";
        public const string GREEN_ITEMS_PLURAL = "AUTO_SCRAPPER_GREEN_ITEMS_PLURAL";
        public const string RED_ITEMS_PLURAL = "AUTO_SCRAPPER_RED_ITEMS_PLURAL";
        public const string YELLOW_ITEMS_PLURAL = "AUTO_SCRAPPER_YELLOW_ITEMS_PLURAL";
        public const string AND = "AUTO_SCRAPPER_AND";
        public const string PROFILE_DESCRIPTION = "AUTO_SCRAPPER_PROFILE_DESCRIPTION";
        public const string AMOUNT_OF_X_TO_KEEP = "AUTO_SCRAPPER_AMOUNT_OF_X_TO_KEEP";
        public const string NUMBER_EXPLANATION = "AUTO_SCRAPPER_NUMBER_EXPLANATION";
        public const string KEEP_SCRAPPER_CLOSED = "AUTO_SCRAPPER_KEEP_SCRAPPER_CLOSED";
        public const string KEEP_SCRAPPER_CLOSED_DESC = "AUTO_SCRAPPER_KEEP_SCRAPPER_CLOSED_DESC";
        public const string MOD_ENABLED = "AUTO_SCRAPPER_MOD_ENABLED";
        public const string MOD_ENABLED_DESC = "AUTO_SCRAPPER_MOD_ENABLED_DESC";
        public const string SCRAP_EVERYTHING = "AUTO_SCRAPPER_SCRAP_EVERYTHING";
        public const string SCRAP_EVERYTHING_DESC = "AUTO_SCRAPPER_SCRAP_EVERYTHING_DESC";
        public const string PROFILE_OVERRIDE = "AUTO_SCRAPPER_PROFILE_OVERRIDE";
        public const string PROFILE_OVERRIDE_DESC = "AUTO_SCRAPPER_PROFILE_OVERRIDE_DESC";
        public static readonly string[] PROFILE_RENAMES = {"AUTO_SCRAPPER_PROFILE_RENAME_1", "AUTO_SCRAPPER_PROFILE_RENAME_2", "AUTO_SCRAPPER_PROFILE_RENAME_3"};
        public static readonly string[] PROFILE_RENAME_DESCS = {"AUTO_SCRAPPER_PROFILE_RENAME_DESC_1", "AUTO_SCRAPPER_PROFILE_RENAME_DESC_2", "AUTO_SCRAPPER_PROFILE_RENAME_DESC_3"};
        public const string CATEGORY_GENERAL = "AUTO_SCRAPPER_CATEGORY_GENERAL";
        public const string CATEGORY_WHITE_ITEMS = "AUTO_SCRAPPER_CATEGORY_WHITE_ITEMS";
        public const string CATEGORY_GREEN_ITEMS = "AUTO_SCRAPPER_CATEGORY_GREEN_ITEMS";
        public const string CATEGORY_RED_ITEMS = "AUTO_SCRAPPER_CATEGORY_RED_ITEMS";
        public const string CATEGORY_YELLOW_ITEMS = "AUTO_SCRAPPER_CATEGORY_YELLOW_ITEMS";
    }
}